### PR TITLE
Change test server to the public orion context broker.

### PR DESCRIPTION
**Pull request by LuisGP**
This PR changes the server using for testing to the public Orion ContextBroker.

**Currently isn't working**
- [ ] Verify that the server works again before merge this PR.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss-fiware-linux/7/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss-fiware-linux/11/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss-fiware-linux/12/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss-fiware-linux/13/)

**Review by lemunozm — APPROVED** [review]

**Comment by MiguelBarro** [comment]
https://github.com/eProsima/FIWARE-SH/pull/36 fixes this issue

**Pull request closed without merging**
